#工作流名字
name: Test

on:
  workflow_dispatch:

#环境变量
env:
  TZ: Asia/Shanghai

#工作
jobs:
  build:
    runs-on: ubuntu-18.04
    #步骤
    steps:
    #检出当前仓库
    - name: Checkout
      uses: actions/checkout@main
      
    #初始化环境变量
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        ln -sf /workdir $GITHUB_WORKSPACE
        echo "DATE=$(date "+%Y-%m-%d %H:%M:%S")" >> $GITHUB_ENV

    #发布到Release    
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ env.DATE }} ❤️
        files: Release.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    #删除旧的Release
    - name: Remove old Releases
      uses: dev-drprasad/delete-older-releases@v0.1.0
      with:
        keep_latest: 7
        delete_tags: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}