#工作流名字
name: Test

on:
  workflow_dispatch:

#环境变量
env:
  TZ: Asia/Shanghai

#工作
jobs:
  build:
    runs-on: ubuntu-18.04
    #步骤
    steps:
    #检出当前仓库
    - name: Checkout
      uses: actions/checkout@main
      
    #初始化环境变量
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        ln -sf /workdir $GITHUB_WORKSPACE